services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
    ports:
      - "8787:8787"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8787/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:80"
