name: CI / Build & Test (web+api)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        node: [22.x]  # 로컬과 동일 (v22)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Print versions
        run: |
          node -v
          npm -v

      # Workspaces 루트에서 한 번만 설치
      - name: Install (root, workspaces)
        run: npm ci --no-audit --no-fund

      # ---- WEB ----
      - name: Build (web)
        working-directory: apps/web
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          # 필요 시 공개가능한 값만 여기에. (비밀키는 secrets 사용)
          # VITE_API_BASE: http://localhost:8787
        run: npm run build

      # ---- API ----
      - name: Typecheck (api)
        working-directory: apps/api
        run: npm run typecheck

      - name: Test (api)
        working-directory: apps/api
        env:
          NODE_ENV: test
        run: npm test --silent
      
      - name: Typecheck (web)
        working-directory: apps/web
        run: npm run typecheck

      - name: Guardrail tests (web)
        working-directory: apps/web
        run: npm test