name: Guard Main
on:
  push:
    branches: [ main ]
jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if direct push to main
        run: |
          echo "Direct push to main detected. Please use PR."
          exit 1
